// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "self"
import "jquery"
import "jquery-ui"
import "jquery_ujs"
import "turbolinks"
import "bootstrap"
import "tree"